"""Migrate users and rooms

Revision ID: 56ab6d6dfc66
Revises: afc254bf90dd
Create Date: 2024-07-18 12:54:22.673595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ab6d6dfc66'
down_revision: Union[str, None] = 'afc254bf90dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
