"""Migrate users, rooms and bookings

Revision ID: c6b62e08b7dc
Revises: 56ab6d6dfc66
Create Date: 2024-07-18 12:56:49.833011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b62e08b7dc'
down_revision: Union[str, None] = '56ab6d6dfc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
